import os
import json
import uuid
import math
import string
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ── Audit Log ────────────────────────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# ── Signal 1: LLM Classification ────────────────────────────────────────────

def llm_signal(text):
    prompt = f"""You are an AI content detection assistant. Analyze the following text and return 
a JSON object with one field: "ai_score" (float 0.0-1.0, where 1.0 means 
highly confident this is AI-generated and 0.0 means highly confident this is 
human-written). Consider: uniformity of sentence structure, presence of generic 
filler phrases, lack of personal voice, and overly balanced hedging.

Text: {text}

Return ONLY valid JSON like this: {{"ai_score": 0.75}}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=50,
    )
    raw = response.choices[0].message.content.strip()
    data = json.loads(raw)
    return float(data["ai_score"])


# ── Signal 2: Stylometric Heuristics ────────────────────────────────────────

def stylometric_signal(text):
    sentences = [s.strip() for s in text.replace("!", ".").replace("?", ".").split(".") if s.strip()]
    words = text.split()

    if len(sentences) < 2 or len(words) < 10:
        return 0.5  # not enough data

    # Sentence length variance (low variance = more AI-like)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # Normalize: std_dev of ~8+ = very human, ~2 or less = AI-like
    variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # Type-token ratio (low TTR = more repetitive = more AI-like)
    unique_words = set(w.lower().strip(string.punctuation) for w in words)
    ttr = len(unique_words) / len(words)
    # Normalize: TTR of 0.8+ = very human, 0.4 or less = AI-like
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.4) / 0.4)))

    # Punctuation density (informal punctuation = more human)
    informal_punct = text.count("—") + text.count("...") + text.count("!") + text.count("?")
    punct_per_word = informal_punct / len(words)
    # Normalize: 0.05+ per word = very human, 0 = AI-like
    punct_score = max(0.0, min(1.0, 1.0 - (punct_per_word / 0.05)))

    combined = (variance_score * 0.5) + (ttr_score * 0.3) + (punct_score * 0.2)
    return round(combined, 3)


# ── Confidence Scoring ───────────────────────────────────────────────────────

def combine_signals(llm_score, stylo_score):
    return round((0.6 * llm_score) + (0.4 * stylo_score), 3)


# ── Transparency Label ───────────────────────────────────────────────────────

def generate_label(confidence):
    pct = round(confidence * 100)
    if confidence >= 0.75:
        return (
            f"⚠️ AI-Generated Content Detected\n"
            f"Our system is highly confident this content was generated by an AI tool "
            f"rather than written by a human. Confidence: {pct}%.\n"
            f"If you are the creator and believe this is incorrect, you may file an appeal."
        )
    elif confidence >= 0.40:
        return (
            f"🔍 Authorship Uncertain\n"
            f"Our system could not confidently determine whether this content was "
            f"human-written or AI-generated. Confidence: {pct}%.\n"
            f"This content has been flagged for transparency. The creator may file an "
            f"appeal to provide additional context."
        )
    else:
        human_pct = round((1 - confidence) * 100)
        return (
            f"✅ Likely Human-Written\n"
            f"Our system believes this content was written by a human creator. "
            f"Confidence: {human_pct}%.\n"
            f"Attribution signals indicate original human authorship."
        )

def get_attribution(confidence):
    if confidence >= 0.75:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"


# ── Routes ───────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = combine_signals(llm_score, stylo_score)
    attribution = get_attribution(confidence)
    label = generate_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 3),
        "stylometric_score": stylo_score,
        "label": label,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    entries = read_log()
    found = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found"}), 404

    write_log(entries)
    return jsonify({
        "appeal_received": True,
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and will be reviewed by a human moderator.",
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-10:]})  # return last 10


if __name__ == "__main__":
    app.run(debug=True)